INSERT INTO NAVOMIN_SUPER.CATEGORY (CATEGORY_NAME)
VALUES ('Grocery'),
('Pre Order');

INSERT INTO NAVOMIN_SUPER.PRODUCT_CATEGORY (CATEGORY_ID, PRODUCTCATEGORY_NAME)
VALUES (1, 'Vegetable'),
(1, 'Fruit'),
(1, 'Dry Food'),
(1, 'Beverage'),
(2, 'Cooked Meal'),
(2, 'Sweets');

INSERT INTO NAVOMIN_SUPER.PRODUCT (PRODUCT_ID, PRODUCTCATEGORY_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION)
VALUES ('V600001', 1, 'Carrot', 'Fresh Up Country Vegetable'),
('C1000001', 5, 'Fish Bun', 'Freshly Backed Fishy Bun');

INSERT INTO NAVOMIN_SUPER.PRODUCT_SIZE (PRODUCT_ID, PRICE, SIZE)
VALUES ('V600001', 200, '500g'),
('V600001', 400, '1kg'),
('C1000001', 80, '1');

INSERT INTO NAVOMIN_SUPER.PRODUCT_IMAGE (PRODUCT_ID, IMAGE_LINK)
VALUES ('V600001', 'https://i.imgur.com/pDlOAlJ.jpeg'),
('C1000001', 'https://i.imgur.com/hpeyFvB.jpg');

INSERT INTO NAVOMIN_SUPER.USER (FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, PHONE_NUMBER)
VALUES ('TEST', 'USER', 'user@gmail.com', 'user@123', '0712223333');